[deps]
CellularAutomata = "878138dc-5b27-11ea-1a71-cb95d38d6b29"
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterCitations = "daee34ce-89f3-4625-b898-19384cb65244"
DocumenterInterLinks = "d12716ef-a0f6-4df4-a9f1-a5a34e75c656"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
ReservoirComputing = "7c2d2b1e-3dd4-11ea-355a-8f6a8116e294"
Static = "aedffcd0-7271-4cad-89d0-dc628f76c6d3"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[sources]
ReservoirComputing = {path = "/var/lib/buildkite-agent/builds/gpuci-16/julialang/reservoircomputing-dot-jl"}

[compat]
CellularAutomata = "0.0.6"
Documenter = "1"
DocumenterCitations = "1"
DocumenterInterLinks = "1"
OrdinaryDiffEq = "6"
Plots = "1"
ReservoirComputing = "0.12.0"
StatsBase = "0.34.4"
